#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const usage = `Embed the built UI into the CLI as a string.

  node scripts/embed-ui.mjs

The CLI ships as a few JS files with no asset directory, so the page has to
travel inside the bundle rather than beside it.`;

if (process.argv.includes('--help')) {
  console.log(usage);
  process.exit(0);
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'apps/ui/dist/index.html'), 'utf8');
const target = join(root, 'apps/cli/src/services/ui/page.ts');

writeFileSync(
  target,
  `// Generated by scripts/embed-ui.mjs from apps/ui — edit the React app, not this.\nexport const PAGE = ${JSON.stringify(html)};\n`,
  'utf8',
);

console.log(`embedded ${(html.length / 1024).toFixed(0)}KB into ${target.replace(`${root}/`, '')}`);
